import { UserId } from "../../user/valueObjects/UserId";
import { RefreshTokenError, RefreshTokenErrorType } from "../enums/RefreshTokenErrorType";

/**
 * @file RefreshToken.ts
 * @description Domain Entity representing a long-lived Refresh Token used for
 * obtaining new Access Tokens without re-authentication.
 * This entity belongs to the Domain layer of the Clean Architecture.
 */
export class RefreshToken {
    /**
     * @property {string} id - Unique identifier for the Refresh Token record (UUID or similar).
     */
    public readonly id: string;

    /**
     * @property {string} tokenString - The actual opaque token value (JWT or random string).
     */
    public readonly tokenString: string;

    /**
     * @property {UserId} userId - The identifier of the user who owns this token.
     */
    public readonly userId: UserId;

    /**
     * @property {Date} expiresAt - The timestamp when this token becomes invalid.
     */
    public expiresAt: Date;

    /**
     * @property {boolean} isRevoked - Flag indicating if the token has been deliberately invalidated (e.g., logout, rotation).
     */
    public isRevoked: boolean;

    /**
     * @property {Date} issuedAt - The timestamp when the token was created.
     */
    public readonly issuedAt: Date;

    /**
     * Private constructor to enforce creation via the static factory method.
     * * @param {string} id - The unique ID of the token record.
     * @param {string} tokenString - The opaque token value.
     * @param {UserId} userId - The ID of the owner user.
     * @param {Date} expiresAt - The expiration date.
     * @param {Date} issuedAt - The issuance date.
     * @param {boolean} isRevoked - Initial revocation status (defaults to false).
     */
    private constructor(
        id: string,
        tokenString: string,
        userId: UserId,
        expiresAt: Date,
        issuedAt: Date,
        isRevoked: boolean = false
    ) {
        this.id = id;
        this.tokenString = tokenString;
        this.userId = userId;
        this.expiresAt = expiresAt;
        this.issuedAt = issuedAt;
        this.isRevoked = isRevoked;
    }

    /**
     * Static factory method to create a new RefreshToken instance.
     * This method ensures the entity invariants are met upon creation.
     * * @param {string} id - A unique ID for the token entity (e.g., UUID generated by the Infrastructure layer).
     * @param {string} tokenString - The token value itself.
     * @param {UserId} userId - The ID of the user.
     * @param {Date} expiresAt - The expiration date.
     * @param {Date} [issuedAt=new Date()] - Optional issuance date, defaults to current time.
     * @returns {RefreshToken} A new RefreshToken entity.
     */
    public static createNew(
        id: string,
        tokenString: string,
        userId: UserId,
        expiresAt: Date,
        issuedAt: Date = new Date()
    ): RefreshToken {
        if (!id || !tokenString || !userId || !(expiresAt instanceof Date) || expiresAt.getTime() <= issuedAt.getTime()) {
            // In a real application, throw a Domain/UserError here
            throw new RefreshTokenError(RefreshTokenErrorType.INVALID_PARAMETERS)
        }
        return new RefreshToken(id, tokenString, userId, expiresAt, issuedAt, false);
    }

    /**
     * Static factory method to recreate an entity from persistent storage (Database/Repository).
     * * @param {string} id - The unique ID of the token record.
     * @param {string} tokenString - The opaque token value.
     * @param {UserId} userId - The ID of the owner user.
     * @param {Date} expiresAt - The expiration date.
     * @param {Date} issuedAt - The issuance date.
     * @param {boolean} isRevoked - The current revocation status.
     * @returns {RefreshToken} A recreated RefreshToken entity.
     */
    public static fromPersistence(
        id: string,
        tokenString: string,
        userId: UserId,
        expiresAt: Date,
        issuedAt: Date,
        isRevoked: boolean
    ): RefreshToken {
        // Validation could be skipped here if the repository guarantees data integrity
        return new RefreshToken(id, tokenString, userId, expiresAt, issuedAt, isRevoked);
    }

    /**
     * Domain method to check if the token is currently active and valid.
     * * @returns {boolean} True if the token is not expired and not revoked.
     */
    public isValid(): boolean {
        const now = new Date();
        // Check if the token is expired OR revoked
        return !this.isRevoked && (this.expiresAt.getTime() > now.getTime());
    }

    /**
     * Domain method to mark the token as permanently invalid.
     * This is typically used during logout or token rotation.
     */
    public revoke(): void {
        this.isRevoked = true;
    }

    /**
     * Domain method to check if the token has expired.
     * @returns {boolean} True if the current time is after the expiration time.
     */
    public isExpired(): boolean {
        const now = new Date();
        return this.expiresAt.getTime() <= now.getTime();
    }
}